### ISSUE TITLE
fork plans?

### ISSUE THREAD

**Issue by marekr** [joro75/wxFormBuilder#4]
I see you made a fork and are working on things. What are your plans? My repo for wxFB was put up on github to support KiCad development because the sourceforge and luamake system is insane.

**Comment by joro75** [comment]
@marekr : I indeed created a fork of your repo, because I want to integrate some improvements in wxFB. 
We are currently using the old wxPython XRCed editor for the software package that my company is selling. The XRCed is not supported anymore, and is not supporting all the modern controls. 
I recently investigated alternatives to XRCed, and found that wxFB is much better. There are however some small problems in it, and I have some idea's to simplify the import of other XRC files.

So the primary goal is to implement some improvements to wxFB, which helps my company to simplify the creation/editing of XRC files.
I'm planning to work on the following steps:
1) Update to future wxWidgets 3.1 (because that is the only one that is working in VS2015) (Already done)
2) Create VS2015 projects to compile wxFB (Already done)
3) Resolve the remaining compiler warnings (~10)
4) Fix the default properties of controls when loaded from XRC
5) Simplify the import of XRC by automatically creating a correct wxFB project

Your repo is hosted on GitHub, and seems to be the most up to date. That you already removed the luamake system is also a benefit for me. That's the reason that I decided to fork from your repository.

Ofcourse I intend to make improvements, that should also be a benefit for you (like the changes to get it running for wxWidgets 3.1). I especially included those changes in a different branch, so simplify the merging.
Is there anything that I can do, to help you?

**Comment by marekr** [comment]
I was just curious seeing the work you were doing. Some of the patches were interesting. Yea the sourceforge upstream with luamake is just horrendous.  

It'll probably be quite awhile though before wxWidgets 3.1 comes out.


Side note, I just pulled in some of latest changes since last august from svn.
